location:
    source_directories:
        - ~/Desktop
        - ~/Documents
        - ~/alice/simulations/

    one_file_system: true

    repositories:
        - t662ah76@t662ah76.repo.borgbase.com:repo

    exclude_caches: true

storage:
    compression: auto,zstd
    encryption_passphrase: CHANGE ME!!
    archive_name_format: '{hostname}-{now}'

retention:
    keep_daily: 2
    keep_weekly: 4
    keep_monthly: 1
    prefix: '{hostname}-'

consistency:
    checks:
        # uncomment to always do integrity checks. (takes long time for large repos)
        #- repository
        - disabled

    prefix: '{hostname}-'